// Code generated by github.com/structcopy/structcopy-gen. DO NOT EDIT.

package standalone

import (
	"github.com/structcopy/structcopy-gen/examples/internal/standalone/dto"
	"github.com/structcopy/structcopy-gen/examples/internal/standalone/entity"
)

func UserToUserDTO(src *entity.User) (dst *dto.UserDTO) {
	dst = &dto.UserDTO{}
	dst.FirstName = src.FirstName
	dst.LastName = TestConvert(src.LastName)
	dst.Email = TestConvert(src.EMail)
	dst.FullName = src.FullName()
	// skip: dst.SkipField

	return
}

func UserToUserDTORaw(src entity.User) (dst dto.UserDTO) {
	dst.FirstName = src.FirstName
	dst.LastName = src.LastName
	// no match: dst.Email
	// no match: dst.FullName
	// no match: dst.SkipField

	return
}

func UserSliceToUserDTOSlice(src []*entity.User) (dst []*dto.UserDTO) {
	if len(src) > 0 {
		dst = make([]*dto.UserDTO, len(src))
		for i, e := range src {
			dst[i] = UserToUserDTO(e)
		}
	}

	return
}

func UserSliceToUserDTOSliceRaw(src []entity.User) (dst []dto.UserDTO) {
	if len(src) > 0 {
		dst = make([]dto.UserDTO, len(src))
		for i, e := range src {
			dst[i] = UserToUserDTORaw(e)
		}
	}

	return
}

func TestToTestDTO(src *Test) (dst *TestDTO) {
	dst = &TestDTO{}
	dst.FirstName = src.FirstName

	return
}

func TestToTestDTORaw(src Test) (dst TestDTO) {
	dst.FirstName = src.FirstName

	return
}
