// Code generated by github.com/bookweb/structcopy-gen. DO NOT EDIT.

package example

import (
	"github.com/bookweb/structcopy-gen/examples/internal/example/dto"
	"github.com/bookweb/structcopy-gen/examples/internal/example/entity"
)

func UserToUserDTO(src *entity.User) (dst *dto.UserDTO) {
	dst = &dto.UserDTO{}
	dst.FirstName = src.FirstName
	dst.LastName = TestConvert(src.LastName)
	dst.Email = TestConvert(src.EMail)
	dst.FullName = src.FullName()

	return
}

func UserToUserDTORaw(src entity.User) (dst dto.UserDTO) {
	dst.FirstName = src.FirstName
	dst.LastName = src.LastName
	dst.Email = src.EMail
	// no match: dst.FullName

	return
}

func UserSliceToUserDTOSlice(src []*entity.User) (dst []*dto.UserDTO) {
	if len(src) > 0 {
		dst = make([]*dto.UserDTO, len(src))
		for i, e := range src {
			dst[i] = UserToUserDTO(e)
		}
	}

	return
}

func UserSliceToUserDTOSliceRaw(src []entity.User) (dst []dto.UserDTO) {
	if len(src) > 0 {
		dst = make([]dto.UserDTO, len(src))
		for i, e := range src {
			dst[i] = UserToUserDTORaw(e)
		}
	}

	return
}
